たまご: 卵
玉子: 卵
牛乳: 乳
ミルク: 乳
乳製品: 乳
蕎麦: そば
ピーナッツ: 落花生
ピーナツ: 落花生
エビ: えび
海老: えび
カニ: かに
蟹: かに
サバ: さば
鯖: さば
アワビ: あわび
鮑: あわび
イカ: いか
烏賊: いか
イクラ: いくら
クルミ: くるみ
胡桃: くるみ
ゴマ: ごま
胡麻: ごま
マツタケ: まつたけ
松茸: まつたけ
ヤマイモ: やまいも
山芋: やまいも
みかん: オレンジ
柑橘: オレンジ
ばなな: バナナ
モモ: もも
桃: もも
リンゴ: りんご
林檎: りんご