##### このYAMLの記述ルール #####
# アンダースコア始まり：N2エクスポートに出力されたくないもの
# typeなし：カスタムフィールドに出力されたくないもの

自治体用:
    自治体確認:
        type: radio
        value: 未
        v-if: n2.settings.N2.自治体確認
        option:
            - 未
            - 確認中
            - 却下
            - 承諾
    却下理由:
        type: textarea
        style: 'width: 100%;'
        v-if: "'却下' === 自治体確認 && n2.settings.N2.自治体確認"
        rows: auto
        "@input": auto_fit_tetxarea($event.target)


スチームシップ用:
    総務省申請:
        type: radio
        value: 未
        option:
            未: 未
            不要: 不要
            申請前: 申請前
            申請中: 申請中
            差戻: 差戻
            却下: 却下
            承認済: 承認済
    総務省申請不要理由:
        type: textarea
        style: 'width: 100%;'
        required: required
        v-if: 総務省申請==='不要'
        rows: auto
        description: 総務省申請で「不要」を選択した場合は必ず記入して下さい。
        "@focus": set_info($event.target)
        "@input": auto_fit_tetxarea($event.target)

    返礼品コード:
        type: text
        description: "[事業者コード3桁アルファベット大文字][3桁数字]で構成"
        placeholder: 例）AAA000
        required: required
        "@focus": set_info($event.target)
        "@change": "force_half_size_text($event, 'uppercase', '返礼品コード')"
    LH表示名:
        type: text
        placeholder: 例）ヒレステーキ 200g
        style: 'width: 100%;'
    寄附金額:
        type: donation-amount
        description: 寄附金額を手動入力したい場合はチェックボックスにチェックを入れてください。<br>チェックが入っていない場合は寄附金額は自動計算されます。
        placeholder: 例）10000
        style: "width: 12em"
        "@focus": "set_info($event.target);tmp.number_format=false"
        "@blur": "tmp.number_format=true"
        :value: 寄附金額
        "@change": "force_half_size_text($event, 'number', '寄附金額');calc_donation(価格, 送料, 定期便)"
    寄附金額固定:  # N2エクスポートに入れるために必須
    出品禁止ポータル:
        label: 出品禁止ポータルサイト
        type: checkbox
        value: []
        description: この返礼品を出品しないポータルサイトがあればチェックを入れてください。
        v-if: "!商品タイプ.includes('eチケット')"
        option:
            - ふるさとチョイス
            - 楽天
        "@mouseover": set_info($event.target)
    オンライン決済限定:
        portal: ふるさとチョイス
        type: checkbox
        value: []
        description: ふるさとチョイスオンライン決済限定に反映されます。
        v-if: "!出品禁止ポータル.includes('ふるさとチョイス')"
        option:
            - 限定
        "@mouseover": set_info($event.target)

# ▼ =========== 楽天専用のフィールド ==========
    全商品ディレクトリID:
        portal: 楽天
        label: ジャンルID
        type: rakuten-genreid
        label: 楽天ジャンルID
        min: 0
        v-if: "!出品禁止ポータル.includes('楽天') && !商品タイプ.includes('eチケット')"
        description: 必ず、ID（6桁の数字）が見えるようになるまで黒いボタンを押していってください。
    商品属性:
        portal: 楽天
        type: rakuten-attributes
        v-model: JSON.stringify(商品属性)
        ':value': JSON.stringify(商品属性)
        v-if: "!出品禁止ポータル.includes('楽天') && !商品タイプ.includes('eチケット') && 全商品ディレクトリID"
        description: 少なくとも必須の商品属性は必ず取得し、保存してください。必須の商品属性が無かった場合は、任意入力になります。
    楽天SPAカテゴリー:
        portal: 楽天
        type: rakuten-spa-category
        v-if: "!出品禁止ポータル.includes('楽天') && tmp.楽天SPA対応  && !商品タイプ.includes('eチケット')"
        style: 'width: 100%;'
        rows: auto
        "@focus": set_info($event.target);get_spa_category();auto_fit_tetxarea($event.target)
        "@input": auto_fit_tetxarea($event.target)
    楽天カテゴリー:
        portal: 楽天
        type: rakuten-category
        v-if: "!出品禁止ポータル.includes('楽天')"
        rows: auto
        style: 'display: none;'

    楽天納期情報:
        portal: 楽天
        type: select
        label: 楽天納期
        v-if: "!出品禁止ポータル.includes('楽天')"
        ':option': tmp.楽天納期情報

# ▲ =========== 楽天専用のフィールド ==========

    検索キーワード:
        type: textarea
        description: 商品名や説明文に入っていないキーワードをスペース区切りで書いてください。
        placeholder: 例）はちみつ 蜂蜜 お歳暮 お中元
        style: 'width: 100%;min-height: 2em;'
        v-if: "!商品タイプ.includes('eチケット')"
        "@focus": set_info($event.target)
        "@input": auto_fit_tetxarea($event.target)

    社内共有事項:
        type: textarea
        description: この商品に関して社内共有すべきことがあればここに記入。
        style: 'width: 100%;'
        rows: auto
        "@focus": set_info($event.target)
        "@input": auto_fit_tetxarea($event.target)

    類型該当理由:
        label: ポータル表示用類型該当理由
        type: textarea
        style: 'width: 100%;'
        description: ポータルに表示されるので、公開して良い情報なのか確認して下さい。
        maxlength: 300
        "@focus": set_info($event.target);
        "@input": auto_fit_tetxarea($event.target)

事業者用:
    地場産品類型:
        type: select
        ':description': n2.custom_field.事業者用.地場産品類型.option[地場産品類型].replace(/当該地方団体の区域|返礼品等を提供する市区町村の区域|当該地方団体/g,n2.town)
        "@mouseover": set_info($event.target);
        option:
            '': 選択して下さい
            1: 1.当該地方団体の区域内において生産されたもの。
            2: 2.当該地方団体の区域内において返礼品等の原材料の主要な部分が生産されたもの。
            3: 3.当該地方団体の区域内において返礼品等の製造、加工その他の工程のうち主要な部分を行うことにより相応の付加価値が生じているもの。
            3（精米）: 3（精米）.地場産品基準第3号ただし書に規定する、当該地方団体が属する都道府県の区域内において生産された玄米を原材料として、当該地方団体の区域内において精白したもの。
            3（熟成肉）: 3（熟成肉）.地場産品基準第3号ただし書に規定する、当該地方団体が属する都道府県の区域内において生産された食肉を原材料として、当該地方団体の区域内において熟成したもの。
            4: 4.返礼品等を提供する市区町村の区域内において生産されたものであって、近隣の他の市区町村の区域内において生産されたものと混在したもの。
            5: 5.地方団体の広報の目的で生産された当該地方団体のキャラクターグッズ、オリジナルグッズその他これらに類するものであって、形状、名称その他の特徴から当該地方団体の独自の返礼品等であることが明白なもの。
            6: 6.前各号に該当する返礼品等と当該返礼品等との間に関連性のあるものとを合わせて提供するものであって、当該返礼品等が主要な部分を占めるもの。
            7: 7.当該地方団体の区域内において提供される役務その他これに準ずるものであって、当該役務の主要な部分が当該地方団体に相当程度関連性のあるもの。
            8イ: 8イ：市区町村が近隣の他の市区町村と共同でこれらの市区町村の区域内において前各号のいずれかに該当するものを共通の返礼品等とするもの。
            8ロ: 8ロ：都道府県が当該都道府県の区域内の複数の市区町村と連携し、<br>当該連携する市区町村の区域内において前各号のいずれかに該当するものを当該都道府県及び当該市区町村の共通の返礼品等とするもの。
            8ハ: 8ハ：都道府県が当該都道府県の区域内の複数の市区町村において地域資源として相当程度認識されているもの及び当該市区町村を認定し、当該地域資源を当該市区町村がそれぞれ返礼品等とするもの。
            9: 9.震災、風水害、落雷、火災その他これらに類する災害により甚大な被害を受けたことにより、その被害を受ける前に提供していた前各号のいずれかに該当する返礼品等を提供することができなくなった場合において、当該返礼品等を代替するものとして提供するもの。
            99: 99.前各号のいずれかに該当する返礼品等とのみ交換させるために提供するもの。
    総務省提出用類型該当理由:
        type: textarea
        style: 'width: 100%;'
        rows: auto
        ':description': (n2.custom_field.事業者用._類型該当理由info.description[地場産品類型] || `地場産品類型${地場産品類型}に該当する理由を書いてください`).replace(/区域/g,n2.town)
        ':placeholder': (n2.custom_field.事業者用._類型該当理由info.placeholder[地場産品類型] || '例）区域が認定した返礼品であるため。').replace(/区域/g,n2.town)
        insert-placeholder: true
        "@focus": set_info($event.target);auto_fit_tetxarea($event.target);
        "@input": auto_fit_tetxarea($event.target)
    # 地場産品類型に該当する理由の注意書きと例文（あえてtypeなしにしてカスタムフィールドとしては出力させない）
    _類型該当理由info:
        description: 
            1: 区域内で生産された農畜産物もしくは水産物の名称をご記載ください。<div class="text-danger fw-bold">※農畜産物/水産物のみを選んでください。また区域内の原材料を用いて区域外で製造・加工等の工程を行ったものは類型2となります。</div>
            2: 区域内で生産された原材料とその原材料が返礼品に占める重量や付加価値の割合をご記載ください。<div class="text-danger fw-bold">※返礼品の重量や付加価値の半分以上が該当原材料によるものである記載が必要。</div>
            3: 区域内で行われた工程の詳細（完成品に至る一連の工程のどの部分を行っているか）をご記載ください。<div class="text-danger fw-bold">※返礼品の重量や付加価値の半分以上が区域内で行われる工程によるものである記載が必要。</div>
        placeholder:
            1: 例）区域内で生産された牛肉であるため。
            2: 例）区域内で生産された牛肉（原材料名を記載）が価格の90％以上を占めるため。
            3: 例）区域外で生産された豚肉を、区域内において切断・調理・袋詰めまでの加工に係る全行程を行うことにより、仕入れ時の価格の2倍以上の付加価値が生じているため。
            4: 例）同じ区域内で肥育後、近隣の複数団体を管轄すると畜場でと畜するため、流通構造上、近隣の団体で肥育された牛肉と混在することが避けられない牛肉
            5: 例）区域の広報の目的で地元事業者らが企画、編集したもので、名称、内容等からも区域独自のものであることが明白であるため
            6: 例）区域内で生産している牛肉（1号該当）に、区域外（○○市又は△△町）で製造された焼肉のたれをセットにして提供するものであるため。【調達費用の内訳　牛肉：3,000円、焼肉のたれ：500円】
            7: 例）役務の主要な部分である宿泊・食事は、区域内の事業者が区域内の宿泊施設で提供するものであるため
            8イ: 例）区域が3号で提供する共通返礼品（区域の同意あり）
            8ロ: 例）区域（もしくは都道府県）が3号で提供する共通返礼品（区域の同意あり）
            8ハ: 例）博多和牛は県産品として認定されているため
            99: 例）区域内で提供される役務や地場産品に対するクーポンであるため　役務や地場産品を中心に取り扱う施設を対象とし、事業所及び寄附者に役務及び地場産品の利用のみと周知を行う。
    定期便:
        type: select
        value: 1
        v-if: "!商品タイプ.includes('eチケット')"
        option:
            1: 定期便では無い
            2: ２回定期便
            3: ３回定期便
            4: ４回定期便
            5: ５回定期便
            6: ６回定期便
            7: ７回定期便
            8: ８回定期便
            9: ９回定期便
            10: １０回定期便
            11: １１回定期便
            12: １２回定期便
            24: ２４回定期便
            36: ３６回定期便
            48: ４８回定期便
        "@change": auto_adjust_price()
    寄附金額:
        type: hidden
        :value: 寄附金額
        v-if: tmp.current_user == 'jigyousya'
    価格:
        type: price
        label: 価格（税込）
        required: required
        placeholder: 例）1000
        description: '商品価格を税込でご記載ください。<br>※寄附金額は自動で算出しますので、入力不要です。<br>※定期便の場合、<b>1回分の価格</b>をご記載ください。'
        style: 'width: 7em'
        :value: 価格
        "@focus": "set_info($event.target);tmp.number_format=false"
        "@blur": "tmp.number_format=true"
        "@change": "force_half_size_text($event, 'number', '価格');auto_adjust_price()"
    価格総額: # N2エクスポートに入れるために必須
    キャッチコピー:
<<<<<<< HEAD
        type: text
        description: こだわりやポイントを端的にご記載ください。
        maxlength: 40
=======
        type : text
        description : こだわりやポイントを端的にご記載ください。
        maxlength : 40
>>>>>>> v1.2
        v-if: "!商品タイプ.includes('eチケット')"
        placeholder: 例）○○にて金賞受賞！溢れる肉汁をご堪能ください！
        style: 'width: 100%'
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
    説明文:
        type: textarea
        rows: auto
        maxlength: 900
        placeholder: '例）

        【メリット】ほおばると口の中に肉汁があふれ出し、思わず笑顔がこぼれるハンバーグです。

        【実績】2022年グルメグランプリのハンバーグ部門にて「金賞」をいただきました！
        
        【アドバンテージ】厳選した黒毛和牛と国産の豚肉を、こだわりの黄金比率で合い挽きすることで、ジューシーさを生み出しています。
        
        【特徴】全国の皆さまの食卓へ「美味しさ」と「安心」をお届けするべく、原材料にはとてもこだわっています。

        【その他】真空パックにてお届けします。温める際は十分に注意して、湯銭してください。'
        insert-placeholder: true
<<<<<<< HEAD
        description: '【メリット】この返礼品を申し込むことで、寄附者が得られる恩恵やハッピーをお書きください。<br>【実績】この返礼品の良さを裏付ける「実績」「口コミ」「施策」等をお書きください。<br>【アドバンテージ】その他の商品よりも特に優れている「こだわり」や「強み」をお書きください。<br>【特徴】返礼品や事業者様の「特徴」「説明」「想い」をお書きください。<br>【その他】上記以外で伝えたいことがあれば、お書きください。'
=======
        description : '【メリット】この返礼品を申し込むことで、寄附者が得られる恩恵やハッピーをお書きください。<br>【実績】この返礼品の良さを裏付ける「実績」「口コミ」「施策」等をお書きください。<br>【アドバンテージ】その他の商品よりも特に優れている「こだわり」や「強み」をお書きください。<br>【特徴】返礼品や事業者様の「特徴」「説明」「想い」をお書きください。<br>【その他】上記以外で伝えたいことがあれば、お書きください。'
>>>>>>> v1.2
        "@focus": set_info($event.target);
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
    内容量・規格等:
        type: textarea
        maxlength: 1000
        rows: auto
        description: 内容量、数量、サイズ、重さなど詳しくお書きください。
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
    原料原産地:
        type: text
        maxlength: 50
        v-if: "!商品タイプ.includes('eチケット')"
        description: 主要となる原料の主要原産地を記載ください。
        placeholder: 例）〇〇県産
        style: 'width: 100%'
        "@focus": set_info($event.target)
        "@input": set_info($event.target)
    加工地:
        type: text
        maxlength: 50
        v-if: "!商品タイプ.includes('eチケット')"
        description: 加工食品の加工地（製造地）を記載ください。
        placeholder: 例）〇〇県〇〇市
        style: 'width: 100%'
        "@focus": set_info($event.target)
        "@input": set_info($event.target)
    商品タイプ:
        type: checkbox
        value: []
        option: 
            - 食品
        "@change": "check_handling_method();check_tax();"
    税率:
        type: radio
        option:
            8: 8%
            10: 10%

# ▼ =========== 食品専用のフィールド ==========
    アレルギー有無確認:
        type: checkbox
        value: ['アレルギー品目あり']
        v-if: 商品タイプ.some(v=>['食品','酒'].includes(v))
        option:
            - アレルギー品目あり
    アレルゲン:
        type: checkbox
        v-if: 商品タイプ.some(v=>['食品','酒'].includes(v)) && アレルギー有無確認.filter(v=>v).length
        required: required
        option:
            - 卵
            - 乳
            - 小麦
            - そば
            - 落花生
            - えび
            - かに
            - さけ（鮭）
            - さば
            - あわび
            - いか
            - いくら
            - 牛肉
            - 豚肉
            - 鶏肉
            - ゼラチン
            - アーモンド
            - カシューナッツ
            - くるみ
            - 大豆
            - ごま
            - まつたけ
            - やまいも
            - オレンジ
            - キウイフルーツ
            - バナナ
            - もも
            - りんご
    アレルゲン注釈:
        type: textarea
        placeholder: 例）同じ工場で〇〇を含む製品を製造しております。
        description: アレルゲンに関連する注釈があれば入力してください。
        rows: auto
        style: 'width: 100%;height: 2em;'
        v-if: 商品タイプ.some(v=>['食品','酒'].includes(v))
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
    賞味期限:
        type: textarea
        placeholder: 例）配送から５日間
        maxlength: 200
        rows: auto
        style: 'width: 100%;'
        v-if: "商品タイプ.some(v=>['食品','酒'].includes(v)) && !商品タイプ.includes('eチケット')"
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
    消費期限:
        type: textarea
        placeholder: 例）冷凍庫９０日間
        style: 'width: 100%;'
        maxlength: 200
        rows: auto
        v-if: "商品タイプ.some(v=>['食品','酒'].includes(v)) && !商品タイプ.includes('eチケット')"
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
# ▲ =========== 食品専用のフィールド ==========

# ▼ =========== やきもの専用のフィールド ==========
    電子レンジ対応:
        type: radio
        value: ○
        v-if: "商品タイプ.includes('やきもの') && !商品タイプ.includes('eチケット')"
        option:
            ○: 対応
            △: 対応（備考あり）
            ×: 非対応
    オーブン対応:
        type: radio
        value: ○
        v-if: "商品タイプ.includes('やきもの') && !商品タイプ.includes('eチケット')"
        option:
            ○: 対応
            △: 対応（備考あり）
            ×: 非対応
    食洗機対応:
        type: radio
        value: ○
        v-if: "商品タイプ.includes('やきもの') && !商品タイプ.includes('eチケット')"
        option:
            ○: 対応
            △: 対応（備考あり）
            ×: 非対応
    対応機器備考:
        type: textarea
        description: 電子レンジ・オーブン・食洗機対応のいずれかで「備考あり」を選択した場合は必ずお書きください。
        v-if: "商品タイプ.includes('やきもの') && !商品タイプ.includes('eチケット')"
        placeholder: 例）2～3分程の電子レンジ使用は可能です。
        style: 'width: 100%;'
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
# ▲ =========== やきもの専用のフィールド ==========

    申込期間:
        type: text
        placeholder: 例）通年4月〜6月など
        style: 'width: 100%'
    配送期間:
        type: textarea
        description: 配送までにかかる最大納期を入力ください。「即納」表記は避けていただき、最短でも1週間前後で入力をお願いいたします。
        maxlength: 200
        v-if: "!商品タイプ.includes('eチケット')"
        placeholder: 例）入金確認後1ヶ月以内にお届けいたします。
        style: 'width: 100%;'
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)
    限定数量:
        type: text
        placeholder: 例）指定なし
    包装対応:
        type: radio
        value: 無し
        v-if: "!商品タイプ.includes('eチケット')"
        option:
            - 無し
            - 有り
    のし対応:
        type: radio
        value: 無し
        v-if: "!商品タイプ.includes('eチケット')"
        option:
            - 無し
            - 有り
    発送方法:
        type: radio
        value: 常温
        v-if: "!商品タイプ.includes('eチケット')"
        option:
            - 常温
            - 冷蔵
            - 冷凍
    発送サイズ:
        type: select
        required: required
        v-if: "!商品タイプ.includes('eチケット')"
        option:
            '': 未選択
            '0100':
                label: ヤマト 宅急便コンパクト
                v-if: 発送方法=='常温' && n2.settings['寄附金額・送料'].送料['0100']
            '0101': ヤマト 60サイズ
            '0102': ヤマト 80サイズ
            '0103': ヤマト 100サイズ
            '0104': ヤマト 120サイズ
            '0105': 
                label: ヤマト 140サイズ
                v-if: 発送方法=='常温'
            '0106': 
                label: ヤマト 160サイズ
                v-if: 発送方法=='常温'
            '0107': 
                label: ヤマト 180サイズ
                v-if: 発送方法=='常温'
            '0108': 
                label: ヤマト 200サイズ
                v-if: 発送方法=='常温'
            レターパックプラス: 
                label: レターパックプラス
                v-if: 発送方法=='常温'&&n2.settings['寄附金額・送料'].送料.レターパックプラス
            レターパックライト: 
                label: レターパックライト
                v-if: 発送方法=='常温'&&n2.settings['寄附金額・送料'].送料.レターパックライト
            ゆうパケット厚さ1cm:
                label: ゆうパケット厚さ1cm
                v-if: 発送方法=='常温'&&n2.settings['寄附金額・送料'].送料.ゆうパケット厚さ1cm
            ゆうパケット厚さ2cm:
                label: ゆうパケット厚さ2cm
                v-if: 発送方法=='常温'&&n2.settings['寄附金額・送料'].送料.ゆうパケット厚さ2cm
            ゆうパケット厚さ3cm:
                label: ゆうパケット厚さ3cm
                v-if: 発送方法=='常温'&&n2.settings['寄附金額・送料'].送料.ゆうパケット厚さ3cm
            その他: その他
        "@change": check_handling_method
    _送料: # 隠し送料
        type: hidden
        name: 送料
        :value: "!商品タイプ.includes('eチケット') ? 送料 : 0"
        required: required
    送料: # 実質その他用送料
        type: text
        name: 送料
        label: 送料
        description: 発送サイズ「その他」を選択の場合は必須項目です
        style: 'width: 6em'
        v-if: 発送サイズ=='その他'
        required: required
        :value: 送料
        "@focus": set_info($event.target)
        "@change": "force_half_size_text($event, 'number', '送料')"
    取り扱い方法:
        type: checkbox
        value: []
        description: 配送時の取り扱い方法で該当するものを選択してください（２つまで）。
        option:
            - ビン・ワレモノ
            - 天地無用
            - 下積み禁止
            - なまもの
            - 精密機器
            - 水濡厳禁
        v-if: "!isNaN(発送サイズ||'未選択')"
        '@click': 'if (取り扱い方法.filter(v=>v).length == 2 ) { $event.target.checked = false; set_info($event.target) }'
    配送伝票表示名:
        type: text
        description: 配送伝票に表示したい自社での品番・名称等がある場合はご記入ください。<br>※特に記載がない場合は、返礼品名の最初の20文字が伝票へ記載されます。
        maxlength: 17
        placeholder: 17文字以内
        style: 'width: 17em;'
        "@focus": set_info($event.target)
        "@input": set_info($event.target)
    LHカテゴリー:
        label: カテゴリー
        type: select
        option:
            - 未選択
            - 肉
            - 魚貝類
            - 野菜・果物
            - 酒
            - 米
            - 卵（鶏、烏骨鶏等）
            - 菓子・飲料類
            - 調味料・油
            - 体験・宿泊
            - 雑貨・日用品・ファッション
            - その他
    提供事業者名:
        type: datalists
        placeholder: 例）〇〇商店
        v-if: n2.settings.N2.提供事業者名
        option: []
    備考欄:
        type: textarea
    商品画像:
        type: item-image
        value: []
        label: 商品画像（8枚以上推奨）
        description: 画像を複数選択、またはアップロードしてください。画像は可能であれば8枚以上を推奨いたします。
    N1zip:
        type: hidden
