スチームシップ用:
    返礼品コード:
        type: text
        description: "[事業者コード3桁アルファベット大文字][3桁数字]で構成"
        placeholder: 例）AAA000
        :value: 返礼品コード
        "@focus": set_info($event.target)
        "@change": "force_half_size_text($event, 'uppercase', '返礼品コード')"

    LH表示名:
        type: text
        placeholder: 例）ヒレステーキ 200g
        style: 'width: 100%;'

    寄附金額:
        type: donation-amount
        description: 寄附金額を手動入力したい場合はチェックボックスにチェックを入れてください。<br>チェックが入っていない場合は寄附金額は自動計算されます。
        placeholder: 例）10000
        style: "width: 12em;"
        "@focus": set_info($event.target)
        :value: 寄附金額
        "@change": "force_half_size_text($event, 'number', '寄附金額');calc_donation(価格, 送料, 定期便)"
    寄附金額固定:  # N2エクスポートに入れるために必須

    全商品ディレクトリID:
        portal: 楽天ふるさと納税
        type: rakuten-genreid
        min: 0
        v-model: 全商品ディレクトリID.text
        v-if: "!出品禁止ポータル.includes('楽天ふるさと納税')"
        description: 下のボタンが無くなるまで押していかないと楽天で地味にエラーが出ます。

    タグID:
        portal: 楽天ふるさと納税
        type: rakuten-tagid
        description: 楽天登録に必要なタグを複数選択します。
        maxlength: 161
        rows: auto
        v-model: タグID.text
        v-if: "!出品禁止ポータル.includes('楽天ふるさと納税')&&全商品ディレクトリID.text"
        style: 'width: 100%;'
        "@focus": set_info($event.target);get_genreid();auto_fit_tetxarea($event.target)


    楽天SPAカテゴリー:
        portal: 楽天ふるさと納税
        type: rakuten-spa-category
        v-model: 楽天SPAカテゴリー.text
        v-if: "!出品禁止ポータル.includes('楽天ふるさと納税') && 楽天SPA"
        style: 'width: 100%;'
        rows: auto
        "@focus": set_info($event.target);get_spa_category();auto_fit_tetxarea($event.target)
        "@input": auto_fit_tetxarea($event.target)

    検索キーワード:
        type: textarea
        description: 商品名や説明文に入っていないキーワードをスペース区切りで書いてください。
        placeholder: 例）はちみつ 蜂蜜 お歳暮 お中元
        style: 'width: 100%;'
        "@focus": set_info($event.target)
        "@input": auto_fit_tetxarea($event.target)

    地場産品類型:
        type: select
        option:
            '': 選択して下さい
            1 : 1.当該地方団体の区域内において生産されたもの。
            2 : 2.当該地方団体の区域内において返礼品等の原材料の主要な部分が生産されたもの。
            3 : 3.当該地方団体の区域内において返礼品等の製造、加工その他の工程のうち主要な部分を行うことにより相応の付加価値が生じているもの。
            4 : 4.返礼品等を提供する市区町村の区域内において生産されたものであって、近隣の他の市区町村の区域内において生産されたものと混在したもの。
            5 : 5.地方団体の広報の目的で生産された当該地方団体のキャラクターグッズ、オリジナルグッズその他これらに類するものであって、形状、名称その他の特徴から当該地方団体の独自の返礼品等であることが明白なもの。
            6 : 6.前各号に該当する返礼品等と当該返礼品等との間に関連性のあるものとを合わせて提供するものであって、当該返礼品等が主要な部分を占めるもの。
            7 : 7.当該地方団体の区域内において提供される役務その他これに準ずるものであって、当該役務の主要な部分が当該地方団体に相当程度関連性のあるもの。
            8イ : 8イ：市区町村が近隣の他の市区町村と共同でこれらの市区町村の区域内において前各号のいずれかに該当するものを共通の返礼品等とするもの。
            8ロ : 8ロ：都道府県が当該都道府県の区域内の複数の市区町村と連携し、<br>当該連携する市区町村の区域内において前各号のいずれかに該当するものを当該都道府県及び当該市区町村の共通の返礼品等とするもの。
            8ハ : 8ハ：都道府県が当該都道府県の区域内の複数の市区町村において地域資源として相当程度認識されているもの及び当該市区町村を認定し、当該地域資源を当該市区町村がそれぞれ返礼品等とするもの。
            9 : 9.震災、風水害、落雷、火災その他これらに類する災害により甚大な被害を受けたことにより、その被害を受ける前に提供していた前各号のいずれかに該当する返礼品等を提供することができなくなった場合において、当該返礼品等を代替するものとして提供するもの。

    類型該当理由:
        type: textarea
        style: 'width: 100%;'
        description: 上記、地場産品類型に該当する理由を書いてください。
        placeholder: 例）〇〇県が認定した返礼品であるため。
        "@focus": set_info($event.target)
        "@input": auto_fit_tetxarea($event.target)

    出品禁止ポータル:
        label: 出品禁止ポータルサイト
        type: checkbox
        value: []
        description: この返礼品を出品しないポータルサイトがあればチェックを入れてください。
        v-model: 出品禁止ポータル
        option:
            - ふるさとチョイス
            - 楽天ふるさと納税
        "@mouseover": set_info($event.target)

    # 事業者確認:
    #     type: checkbox
    #     option:
    #         - 確認済み

    社内共有事項:
        type: textarea
        description: この商品に関して社内共有すべきことがあればここに記入。
        style: 'width: 100%;'
        rows: auto
        "@focus": set_info($event.target)
        "@input": auto_fit_tetxarea($event.target)


事業者用:
    寄附金額:
        type: hidden
        :value: 寄附金額
        v-if: current_user == 'jigyousya'

    価格:
        type : text
        # step: 300
        label : 価格（税込）
        required: required
        placeholder: 例）1000
        description: '商品価格を税込でご記載ください。<br>※寄附金額は自動で算出しますので、入力不要です。<br>※定期便の場合、1回分の価格をご記載ください。'
        style: 'width: 10em'
        :value: 価格
        "@focus": set_info($event.target)
        "@change": "force_half_size_text($event, 'number', '価格')"

    キャッチコピー:
        type : text
        description : こだわりやポイントを端的にご記載ください。
        maxlength : 30
        placeholder: 例）○○にて金賞受賞！溢れる肉汁をご堪能ください！
        style: 'width: 100%'
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)

    説明文:
        type : item-description
        rows: auto
        maxlength : 900
        placeholder: '例）

        【メリット】ほおばると口の中に肉汁があふれ出し、思わず笑顔がこぼれるハンバーグです。

        【実績】2022年グルメグランプリのハンバーグ部門にて「金賞」をいただきました！
        
        【アドバンテージ】厳選した黒毛和牛と国産の豚肉を、こだわりの黄金比率で合い挽きすることで、ジューシーさを生み出しています。
        
        【特徴】全国の皆さまの食卓へ「美味しさ」と「安心」をお届けするべく、原材料にはとてもこだわっています。

        【その他】真空パックにてお届けします。温める際は十分に注意して、湯銭してください。'
        description : '【メリット】この返礼品を申し込むことで、寄附者が得られる恩恵やハッピーをお書きください。<br>【実績】この返礼品の良さを裏付ける「実績」「口コミ」「施策」等をお書きください。<br>【アドバンテージ】その他の商品よりも特に優れている「こだわり」や「強み」をお書きください。<br>【特徴】返礼品や事業者様の「特徴」「説明」「想い」をお書きください。<br>【その他】上記以外で伝えたいことがあれば、お書きください。'
        "@focus": set_info($event.target);
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)

    内容量・規格等:
        type : textarea
        maxlength : 1000
        rows: auto
        description : 内容量、数量、サイズ、重さなど詳しくお書きください。
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)

    原料原産地:
        type : text
        maxlength : 50
        description : 主要となる原料の主要原産地を記載ください。
        placeholder: 例）〇〇県産
        style: 'width: 100%'
        "@focus": set_info($event.target)
        "@input": set_info($event.target)

    加工地:
        type : text
        maxlength : 50
        description : 加工食品の加工地（製造地）を記載ください。
        placeholder: 例）〇〇県〇〇市
        style: 'width: 100%'
        "@focus": set_info($event.target)
        "@input": set_info($event.target)

    商品タイプ:
        type : checkbox
        value: []
        v-model: 商品タイプ
        option : 
            - 食品

    アレルギー有無確認:
        type : checkbox
        value: ['アレルギー品目あり']
        v-model: アレルギー有無確認
        v-if: 商品タイプ.includes('食品')
        required: required
        option :
            - アレルギー品目あり

    アレルゲン:
        type : checkbox
        v-if: 商品タイプ.includes('食品')&&アレルギー有無確認.filter(v=>v).length
        required: required
        option :
            - 卵
            - 乳
            - 小麦
            - そば
            - 落花生
            - えび
            - かに
            - さけ（鮭）
            - さば
            - あわび
            - いか
            - いくら
            - 牛肉
            - 豚肉
            - 鶏肉
            - ゼラチン
            - アーモンド
            - カシューナッツ
            - くるみ
            - 大豆
            - ごま
            - まつたけ
            - やまいも
            - オレンジ
            - キウイフルーツ
            - バナナ
            - もも
            - りんご

    アレルゲン注釈:
        type : text
        description : アレルギー品目なしの場合でもなにか特記があればご記載ください。
        placeholder: 例）同じ工場で〇〇を含む製品を製造しております。
        style: 'width: 100%'
        v-if: 商品タイプ.includes('食品')
        "@focus": set_info($event.target)

    賞味期限:
        type : textarea
        placeholder : 例）配送から５日間
        maxlength : 200
        rows: auto
        style: 'width: 100%;'
        v-if: 商品タイプ.includes('食品')
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)

    消費期限:
        type : textarea
        placeholder : 例）冷凍庫９０日間
        style: 'width: 100%;'
        maxlength : 200
        rows: auto
        v-if: 商品タイプ.includes('食品')
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)

    アレルゲン注釈:
        type: textarea
        placeholder: 例）同じ工場で〇〇を含む製品を製造しております。
        description: アレルゲンに関連する注釈があれば入力してください。
        rows: auto
        style: 'width: 100%;height: 2em;'
        v-if: 商品タイプ.includes('食品')
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)

    申込期間:
        type : text
        placeholder : 例）通年4月〜6月など
        style: 'width: 100%'

    配送期間:
        type : textarea
        description : 配送までにかかる最大納期を入力ください。「即納」表記は避けていただき、最短でも1週間前後で入力をお願いいたします。
        maxlength : 200
        placeholder: 例）入金確認後1ヶ月以内にお届けいたします。
        style: 'width: 100%;'
        "@focus": set_info($event.target)
        "@input": set_info($event.target);auto_fit_tetxarea($event.target)

    限定数量:
        type : text
        placeholder : 例）指定なし

    包装対応:
        type: radio
        value: 無し
        option:
            - 無し
            - 有り

    のし対応:
        type: radio
        value: 無し
        option:
            - 無し
            - 有り

    発送方法:
        type : radio
        value: 常温
        option :
            - 常温
            - 冷蔵
            - 冷凍
        v-model: 発送方法

    発送サイズ:
        type : select
        required: required
        option :
            '': 未選択
            '0101': ヤマト 60サイズ
            '0102': ヤマト 80サイズ
            '0103': ヤマト 100サイズ
            '0104': ヤマト 120サイズ
            '0105': 
                label: ヤマト 140サイズ
                v-if: 発送方法=='常温'
            '0106': 
                label: ヤマト 160サイズ
                v-if: 発送方法=='常温'
            '0107': 
                label: ヤマト 180サイズ
                v-if: 発送方法=='常温'
            '0108': 
                label: ヤマト 200サイズ
                v-if: 発送方法=='常温'
            レターパックプラス: 
                label: レターパックプラス
                v-if: 発送方法=='常温'&&n2.delivery_fee.レターパックプラス
            レターパックライト: 
                label: レターパックライト
                v-if: 発送方法=='常温'&&n2.delivery_fee.レターパックライト
            その他: その他
        v-model: 発送サイズ

    送料:
        type: hidden
        :value: 送料
        required: required

    その他送料:
        type : text
        label: 送料
        description: 発送サイズ「その他」を選択の場合は必須項目です
        style: 'width: 6em'
        v-if: 発送サイズ=='その他'
        :value: その他送料
        "@change": "force_half_size_text($event, 'number', 'その他送料')"

    取り扱い方法:
        type : checkbox
        value: []
        description : 配送時の取り扱い方法で該当するものを選択してください（２つまで）。
        option :
            - ビン・ワレモノ
            - 天地無用
            - 下積み禁止
            - なまもの
            - 精密機器
            - 水濡厳禁
        v-if: "!['','その他', 'レターパックプラス', 'レターパックライト'].includes(発送サイズ)"
        v-model: 取り扱い方法
        '@click': 'if (取り扱い方法.filter(v=>v).length == 2 ) { $event.target.checked = false; set_info($event.target) }'

    配送伝票表示名:
        type : text
        description : 配送伝票に表示したい自社での品番・名称等がある場合はご記入ください。<br>※特に記載がない場合は、返礼品名の最初の20文字が伝票へ記載されます。
        maxlength : 17
        placeholder : 17文字以内
        style: 'width: 17em;'
        "@focus": set_info($event.target)
        "@input": set_info($event.target)

    定期便:
        type : select
        value: 1
        option :
            1: 定期便では無い
            2: ２回定期便
            3: ３回定期便
            4: ４回定期便
            5: ５回定期便
            6: ６回定期便
            7: ７回定期便
            8: ８回定期便
            9: ９回定期便
            10: １０回定期便
            11: １１回定期便
            12: １２回定期便
        v-model: 定期便

    LHカテゴリー:
        label: カテゴリー
        type : select
        option :
            - 未選択
            - 肉
            - 魚貝類
            - 野菜・果物
            - 酒
            - 米
            - 卵（鶏、烏骨鶏等）
            - 菓子・飲料類
            - 調味料・油
            - 体験・宿泊
            - 雑貨・日用品・ファッション
            - その他

    商品画像:
        type : item-image
        value: []
        label : 商品画像（8枚以上推奨）
        description : 画像を複数選択、またはアップロードしてください。画像は可能であれば8枚以上を推奨いたします。

    N1zip:
        type: hidden