# 【基本】
# model      : 必須。使用モデル（gpt-4-1106-preview, gpt-3.5-turbo-1106など）
# temperature: 任意。温度感。創造度を0~1のfloatで指定。これが少ないほど機械的に、多いほど創造的になる。
# max_tokens : 任意。トークン数の上限。大体文字数x0.9=トークン数。なので1000トークン=900文字。モデルごとにトークンで課金されるので登録推奨。
# system     : 任意。GPTに提供したい前情報。どのように振舞って欲しいかを文章で定義する。
#
# 【その他】
# stream     : 任意。bool。ChatGPTのように逐次応答する。文章生成が目の前で進んでいく感じでレスポンスを提供。cURL拡張の使用が必要。
# tools      : 任意。回答に際して発火する関数をOpenAIサーバー側に生成する。機能をリクエストで指定して送ることで生成。
#
# [他にも色々](https://platform.openai.com/docs/api-reference/chat/create)


テストプロンプト:
  model: gpt-3.5-turbo-1106
  temperature: 0.5
  max_tokens: 2000
  system_message: うんこを我慢している人になり切って回答してください。

# コンテンツ生成:
#   model: text-davinci-003
#   temperature: 0.5
#   max_tokens: 300
#   system_message: |
#       次のトピックに基づいて記事を生成してください。
#       トピック: {topic}
#       キーワード: {keywords}

# データ分析:
#   model: text-davinci-003
#   temperature: 0.3
#   max_tokens: 100
#   system_message: |
#       次のデータに基づいて分析を行い、洞察を提供してください。
#       データ: {data}
      