choice :
    tsv_header :
        title : チョイス
        value0 :
        - （必須）容量単位
        - （必須）発送期日種別
        - （必須）会員限定
        - （必須）チョイス限定
        - （必須）オンライン決済限定
        - （必須）配送業者
        - （必須）配達日種別
        - （必須）配達日種別必須フラグ
        - （必須）配達時間指定
        - （必須）配達時間指定必須フラグ
        value1 :
        - （必須）別送対応
        - （必須）ポイント情報表示有無
        - （必須）即時交換可否
        - （必須）表示有無
        - （必須）還元率入力有無
    auth :
        user : guest
        pass : guest
        url : https://www.furusato-cms.jp/files/sample_stg_product_details.tsv