# :==================================================

# 発送サイズ、発送方法の組み合わせごとの送料設定

# :==================================================

# 常温時
normal:
    未選択 : ''
    60サイズ : 1000
    80サイズ : 1100
    100サイズ : 1200
    120サイズ : 1300
    140サイズ : 1400
    160サイズ : 1500
    180サイズ : 1600
    200サイズ : 1700
    レターパックプラス : 520
    その他 : 0

# 冷蔵 or 冷凍
# すでに加算されているので注意
cool:
    未選択 : ''
    60サイズ : 1200
    80サイズ : 1300
    100サイズ : 1500
    120サイズ : 1900
    レターパックプラス : 520
    その他 : 0