# ===================================================

# デフォルトカスタムフィールド(返礼品詳細)

# ******* 記述法 ********
# type:text,textarea,checkbox,selectのいずれかを指定
# description:タイトル下の説明文（改行はを書く）
# maxlength:文字数制限
# option:selectとcheckboxの選択肢を指定
# default:text,textareaのデフォルト値を指定
# placeholder:text,textareaのplaceholderを指定

# ===================================================

#変更不可（隠しフィールド）
事業者確認:
    type: checkbox
    option-equal: true
    option:
        - 確認済み

#共通
出品禁止ポータル:
    label: 出品禁止ポータルサイト
    type: checkbox
    option-equal: true
    description: この返礼品を出品しないポータルサイトがあればチェックを入れてください。
    v-model: 出品禁止ポータル
    option:
        - ふるさとチョイス
        - 楽天ふるさと納税
    "@mouseover": set_info($event.target)

価格:
    type : number
    min: 0
    # step: 300
    label : 価格（税込）
    required: required
    placeholder: 例）1000
    description: 上代を税込でご記載ください。定期便の場合、1回分の価格をご記載ください。
    style: 'width: 10em'
    v-model: 価格
    "@focus": set_info($event.target)

キャッチコピー:
    type : text
    description : こだわりやポイントを端的にご記載ください。
    maxlength : 30
    placeholder: 例）「バナナマンのせっかくグルメ！！」「王様のブランチ」で紹介！
    style: 'width: 100%'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

説明文:
    type : textarea
    maxlength : 900
    placeholder: '【こだわり】あなたの仕事や商品に対するこだわりや想いを書いてください。

【強み・特徴】商品のアピールポイントを書いてください。

【用途・恩恵】寄附者が得られるもの、寄附者に届けたいハッピーを書いてください。

【口コミ】お客様から寄せられる声をわかる範囲で具体的（性別、年代、家族構成、購入理由、感想など）に書いてください。

【その他】上記以外で伝えたいことがあれば教えてください。'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

内容量・規格等:
    type : textarea
    maxlength : 1000
    description : 内容量、数量、サイズ、重さなど詳しくお書きください。<br>※器の容量は「満量時」でご記入ください！　満量時ではない場合は「8分目」など必ずどの分量かがわかるようにお願いいたします。<br>※色・柄・セットの商品を登録する場合は、必ず別の商品として登録していただくようお願いいたします（注文時に色などを選択していただくような形式には対応しておりません）。
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

原料原産地:
    type : text
    maxlength : 50
    description : 主要となる原料の主要原産地を記載ください。
    placeholder: 例）〇〇県産
    style: 'width: 100%'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

加工地:
    type : text
    maxlength : 50
    description : 加工食品の加工地（製造地）を記載ください。
    placeholder: 例）〇〇県〇〇市
    style: 'width: 100%'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

商品タイプ:
    type : checkbox
    option-equal: true
    v-model: 商品タイプ
    option : 
        - 食品

アレルギー有無確認:
    type : checkbox
    v-model: アレルギー有無確認
    v-if: 商品タイプ.includes('食品')
    option :
        - アレルギー品目あり

アレルゲン:
    type : checkbox2
    v-if: 商品タイプ.includes('食品')&&アレルギー有無確認
    option :
        0: 卵
        1: 乳
        2: 小麦
        3: そば
        4: 落花生
        5: えび
        6: かに
        7: さけ（鮭）
        8: さば
        9: あわび
        10: いか
        11: いくら
        12: 牛肉
        13: 豚肉
        14: 鶏肉
        15: ゼラチン
        16: アーモンド
        17: カシューナッツ
        18: くるみ
        19: 大豆
        20: ごま
        21: まつたけ
        22: やまいも
        23: オレンジ
        24: キウイフルーツ
        25: バナナ
        26: もも
        27: りんご

アレルゲン注釈:
    type : text
    description : アレルギー品目なしの場合でもなにか特記があればご記載ください。
    placeholder: 例）同じ工場で〇〇を含む製品を製造しております。
    style: 'width: 100%'
    v-if: 商品タイプ.includes('食品')
    "@focus": set_info($event.target)

賞味期限:
    type : textarea
    placeholder : 例）配送から５日間
    maxlength : 200
    style: 'width: 100%;height: 5em;'
    v-if: 商品タイプ.includes('食品')
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

消費期限:
    type : textarea
    placeholder : 例）冷凍庫９０日間
    style: 'width: 100%;height: 5em;'
    maxlength : 200
    v-if: 商品タイプ.includes('食品')
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

アレルゲン注釈:
    type: textarea
    placeholder: 例）同じ工場で〇〇を含む製品を製造しております。
    description: アレルゲンに関連する注釈があれば入力してください。
    style: 'width: 100%;height: 2em;'
    v-if: 商品タイプ.includes('食品')

申込期間:
    type : text
    placeholder : 例）通年4月〜6月など
    default : 通年
    style: 'width: 100%'

配送期間:
    type : textarea
    description : 発送までにかかる最大納期を入力ください。「即納」表記は避けていただき、最短でも2週間以内で入力をお願いいたします。
    maxlength : 200
    required: required
    placeholder: 例）入金確認後1ヶ月以内にお届けいたします。
    style: 'width: 100%;height: 5em;'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

限定数量:
    type : text
    placeholder : 例）指定なし

のし対応:
    type: radio
    value: 無し
    option-equal: true
    option:
        - 無し
        - 有り

発送方法:
    type : radio
    value: 常温
    option-equal: true
    option :
        - 常温
        - 冷蔵
        - 冷凍
    v-model: 発送方法

発送サイズ:
    type : select
    option :
        '': 未選択
        '0101': ヤマト 60サイズ
        '0102': ヤマト 80サイズ
        '0103': ヤマト 100サイズ
        '0104': ヤマト 120サイズ
        '0105': 
            label: ヤマト 140サイズ
            v-if: 発送方法=='常温'
        '0106': 
            label: ヤマト 160サイズ
            v-if: 発送方法=='常温'
        '0107': 
            label: ヤマト 180サイズ
            v-if: 発送方法=='常温'
        '0108': 
            label: ヤマト 200サイズ
            v-if: 発送方法=='常温'
        レターパックプラス: 
            label: レターパックプラス
            v-if: 発送方法=='常温'
        レターパックライト: 
            label: レターパックライト
            v-if: 発送方法=='常温'
        その他: その他
    required: required
    v-model: 発送サイズ

送料:
    type : number
    value : 0
    description: '送料はサイズ等を元に計算された金額が自動で設定されています。'
    style: 'width: 6em'
    v-if: 発送サイズ!=''
    v-model: 送料
    ':readonly': "発送サイズ!='その他' ? true: false"
    "@focus": if (発送サイズ!='その他') { set_info($event.target) }

取り扱い方法:
    type : checkbox
    description : 配送時の取り扱い方法で該当するものを選択してください（２つまで）。
    option-equal: true
    option :
        - ビン・ワレモノ
        - 天地無用
        - 下積み禁止
        - なまもの
        - 精密機器
        - 水濡厳禁
    v-if: "!['','その他', 'レターパックプラス', 'レターパックライト'].includes(発送サイズ)"
    v-model: 取り扱い方法
    '@click': 'if (取り扱い方法.length == 2 ) { $event.target.checked = false; set_info($event.target) }'

配送伝票表示名:
    type : text
    description : 配送伝票に表示したい自社での品番・名称等がある場合はご記入ください。
    maxlength : 20
    placeholder : 20文字以内
    style: 'width: 20em;'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

定期便:
    type : select
    option :
        1: 定期便では無い
        2: ２回定期便
        3: ３回定期便
        4: ４回定期便
        5: ５回定期便
        6: ６回定期便
        7: ７回定期便
        8: ８回定期便
        9: ９回定期便
        10: １０回定期便
        11: １１回定期便
        12: １２回定期便
    required: required
    v-model: 定期便

LHカテゴリー:
    label: カテゴリー
    type : select
    option-equal: true
    option :
        - 未選択
        - 肉
        - 魚貝類
        - 野菜・果物
        - 酒
        - 米
        - 卵（鶏、烏骨鶏等）
        - 菓子・飲料類
        - 調味料・油
        - 体験・宿泊
        - 雑貨・日用品・ファッション
        - その他

商品画像:
    type : item-image
    label : 商品画像（8枚以上推奨）
    description : 画像を複数選択、またはアップロードしてください。画像は可能であれば8枚以上を推奨いたします。
