# ===================================================

# 事業者用カスタムフィールド
#---------------------------
# そのままフィールド名となる
# typeでtemplate/forms/以下のphpファイル名を利用
# nameとlabelを変えたい場合はlabelを設定
# 属性値を自動的に追加

# ===================================================
寄附金額:
    type: hidden
    :value: 寄附金額
    v-if: current_user == 'jigyousya'

価格:
    type : text
    # step: 300
    label : 価格（税込）
    required: required
    placeholder: 例）1000
    description: '商品価格を税込でご記載ください。<br>※寄附金額は自動で算出しますので、入力不要です。<br>※定期便の場合、1回分の価格をご記載ください。'
    style: 'width: 10em'
    :value: 価格
    "@focus": set_info($event.target)
    "@input": "force_half_size_text($event, 'number', '価格')"

キャッチコピー:
    type : text
    description : こだわりやポイントを端的にご記載ください。
    maxlength : 30
    placeholder: 例）○○にて金賞受賞！溢れる肉汁をご堪能ください！
    style: 'width: 100%'
    "@focus": set_info($event.target)
    "@input": set_info($event.target);auto_fit_tetxarea($event.target)

説明文:
    type : textarea
    rows: auto
    maxlength : 900
    placeholder: '例）

    【メリット】ほおばると口の中に肉汁があふれ出し、思わず笑顔がこぼれるハンバーグです。

    【実績】2022年グルメグランプリのハンバーグ部門にて「金賞」をいただきました！
    
    【アドバンテージ】厳選した黒毛和牛と国産の豚肉を、こだわりの黄金比率で合い挽きすることで、ジューシーさを生み出しています。
    
    【特徴】全国の皆さまの食卓へ「美味しさ」と「安心」をお届けするべく、原材料にはとてもこだわっています。

    【その他】真空パックにてお届けします。温める際は十分に注意して、湯銭してください。'
    description : '【メリット】この返礼品を申し込むことで、寄附者が得られる恩恵やハッピーをお書きください。<br>【実績】この返礼品の良さを裏付ける「実績」「口コミ」「施策」等をお書きください。<br>【アドバンテージ】その他の商品よりも特に優れている「こだわり」や「強み」をお書きください。<br>【特徴】返礼品や事業者様の「特徴」「説明」「想い」をお書きください。<br>【その他】上記以外で伝えたいことがあれば、お書きください。'
    value: '例）

    【メリット】ほおばると口の中に肉汁があふれ出し、思わず笑顔がこぼれるハンバーグです。

    【実績】2022年グルメグランプリのハンバーグ部門にて「金賞」をいただきました！
    
    【アドバンテージ】厳選した黒毛和牛と国産の豚肉を、こだわりの黄金比率で合い挽きすることで、ジューシーさを生み出しています。
    
    【特徴】全国の皆さまの食卓へ「美味しさ」と「安心」をお届けするべく、原材料にはとてもこだわっています。
    
    【その他】真空パックにてお届けします。温める際は十分に注意して、湯銭してください。'
    "@focus": set_info($event.target);
    "@input": set_info($event.target);auto_fit_tetxarea($event.target)

内容量・規格等:
    type : textarea
    maxlength : 1000
    rows: auto
    description : 内容量、数量、サイズ、重さなど詳しくお書きください。
    "@focus": set_info($event.target)
    "@input": set_info($event.target);auto_fit_tetxarea($event.target)

原料原産地:
    type : text
    maxlength : 50
    description : 主要となる原料の主要原産地を記載ください。
    placeholder: 例）〇〇県産
    style: 'width: 100%'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

加工地:
    type : text
    maxlength : 50
    description : 加工食品の加工地（製造地）を記載ください。
    placeholder: 例）〇〇県〇〇市
    style: 'width: 100%'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

商品タイプ:
    type : checkbox
    value: []
    option-equal: true
    v-model: 商品タイプ
    option : 
        - 食品

アレルギー有無確認:
    type : checkbox
    value: []
    v-model: アレルギー有無確認
    v-if: 商品タイプ.includes('食品')
    option :
        - アレルギー品目あり

アレルゲン:
    type : checkbox2
    v-if: 商品タイプ.includes('食品')&&アレルギー有無確認.filter(v=>v).length
    option :
        0: 卵
        1: 乳
        2: 小麦
        3: そば
        4: 落花生
        5: えび
        6: かに
        7: さけ（鮭）
        8: さば
        9: あわび
        10: いか
        11: いくら
        12: 牛肉
        13: 豚肉
        14: 鶏肉
        15: ゼラチン
        16: アーモンド
        17: カシューナッツ
        18: くるみ
        19: 大豆
        20: ごま
        21: まつたけ
        22: やまいも
        23: オレンジ
        24: キウイフルーツ
        25: バナナ
        26: もも
        27: りんご

アレルゲン注釈:
    type : text
    description : アレルギー品目なしの場合でもなにか特記があればご記載ください。
    placeholder: 例）同じ工場で〇〇を含む製品を製造しております。
    style: 'width: 100%'
    v-if: 商品タイプ.includes('食品')
    "@focus": set_info($event.target)

賞味期限:
    type : textarea
    placeholder : 例）配送から５日間
    maxlength : 200
    rows: auto
    style: 'width: 100%;'
    v-if: 商品タイプ.includes('食品')
    "@focus": set_info($event.target)
    "@input": set_info($event.target);auto_fit_tetxarea($event.target)

消費期限:
    type : textarea
    placeholder : 例）冷凍庫９０日間
    style: 'width: 100%;'
    maxlength : 200
    rows: auto
    v-if: 商品タイプ.includes('食品')
    "@focus": set_info($event.target)
    "@input": set_info($event.target);auto_fit_tetxarea($event.target)

アレルゲン注釈:
    type: textarea
    placeholder: 例）同じ工場で〇〇を含む製品を製造しております。
    description: アレルゲンに関連する注釈があれば入力してください。
    rows: auto
    style: 'width: 100%;height: 2em;'
    v-if: 商品タイプ.includes('食品')
    "@focus": set_info($event.target)
    "@input": set_info($event.target);auto_fit_tetxarea($event.target)

申込期間:
    type : text
    placeholder : 例）通年4月〜6月など
    style: 'width: 100%'

配送期間:
    type : textarea
    description : 配送までにかかる最大納期を入力ください。「即納」表記は避けていただき、最短でも1週間前後で入力をお願いいたします。
    maxlength : 200
    placeholder: 例）入金確認後1ヶ月以内にお届けいたします。
    style: 'width: 100%;'
    "@focus": set_info($event.target)
    "@input": set_info($event.target);auto_fit_tetxarea($event.target)

限定数量:
    type : text
    placeholder : 例）指定なし

のし対応:
    type: radio
    value: 無し
    option-equal: true
    option:
        - 無し
        - 有り

発送方法:
    type : radio
    value: 常温
    option-equal: true
    option :
        - 常温
        - 冷蔵
        - 冷凍
    v-model: 発送方法

発送サイズ:
    type : select
    option :
        '': 未選択
        '0101': ヤマト 60サイズ
        '0102': ヤマト 80サイズ
        '0103': ヤマト 100サイズ
        '0104': ヤマト 120サイズ
        '0105': 
            label: ヤマト 140サイズ
            v-if: 発送方法=='常温'
        '0106': 
            label: ヤマト 160サイズ
            v-if: 発送方法=='常温'
        '0107': 
            label: ヤマト 180サイズ
            v-if: 発送方法=='常温'
        '0108': 
            label: ヤマト 200サイズ
            v-if: 発送方法=='常温'
        レターパックプラス: 
            label: レターパックプラス
            v-if: 発送方法=='常温'&&n2.delivery_fee.レターパックプラス
        レターパックライト: 
            label: レターパックライト
            v-if: 発送方法=='常温'&&n2.delivery_fee.レターパックライト
        その他: その他
    v-model: 発送サイズ

送料:
    type : text
    description: '送料はサイズ等を元に計算された金額が自動で設定されています。'
    style: 'width: 6em'
    # v-if: 発送サイズ!=''
    :value: 送料
    ':readonly': "発送サイズ!='その他' ? true: false"
    "@focus": if (発送サイズ!='その他') { set_info($event.target) }
    "@input": "force_half_size_text($event, 'number', '送料')"
    required: required

取り扱い方法:
    type : checkbox
    value: []
    description : 配送時の取り扱い方法で該当するものを選択してください（２つまで）。
    option-equal: true
    option :
        - ビン・ワレモノ
        - 天地無用
        - 下積み禁止
        - なまもの
        - 精密機器
        - 水濡厳禁
    v-if: "!['','その他', 'レターパックプラス', 'レターパックライト'].includes(発送サイズ)"
    v-model: 取り扱い方法
    '@click': 'if (取り扱い方法.filter(v=>v).length == 2 ) { $event.target.checked = false; set_info($event.target) }'

配送伝票表示名:
    type : text
    description : 配送伝票に表示したい自社での品番・名称等がある場合はご記入ください。<br>※特に記載がない場合は、返礼品名の最初の20文字が伝票へ記載されます。
    maxlength : 20
    placeholder : 20文字以内
    style: 'width: 20em;'
    "@focus": set_info($event.target)
    "@input": set_info($event.target)

定期便:
    type : select
    value: 1
    option :
        1: 定期便では無い
        2: ２回定期便
        3: ３回定期便
        4: ４回定期便
        5: ５回定期便
        6: ６回定期便
        7: ７回定期便
        8: ８回定期便
        9: ９回定期便
        10: １０回定期便
        11: １１回定期便
        12: １２回定期便
    v-model: 定期便

LHカテゴリー:
    label: カテゴリー
    type : select
    option-equal: true
    option :
        - 未選択
        - 肉
        - 魚貝類
        - 野菜・果物
        - 酒
        - 米
        - 卵（鶏、烏骨鶏等）
        - 菓子・飲料類
        - 調味料・油
        - 体験・宿泊
        - 雑貨・日用品・ファッション
        - その他

商品画像:
    type : item-image
    value: []
    label : 商品画像（8枚以上推奨）
    description : 画像を複数選択、またはアップロードしてください。画像は可能であれば8枚以上を推奨いたします。
