ledghome:
    csv_header :
        title: "LedgHOMEクラウド謝礼品リスト"
        values:
        - 謝礼品番号
        - 取扱年度
        - 謝礼品名
        - 謝礼品名カナ
        - 配送名称
        - ふるさとチョイス名称
        - エフレジ名称
        - 楽天名称
        - ANA名称
        - 事業者
        - 謝礼品カテゴリー
        - セット内容
        - 謝礼品紹介文
        - ステータス
        - 状態
        - 寄附設定金額
        - 価格（税込み）
        - その他経費
        - 送料
        - 送料反映
        - 発送方法
        - 取り扱い方法
        - 申込可能期間
        - 申込可能期間（開始日）
        - 申込可能期間（終了日）
        - 数量限定
        - 自由入力欄1
        - 自由入力欄2
        - その他名称1
        - その他名称2
        - その他名称3
        - 出荷依頼操作期間（開始日）
        - 出荷依頼操作期間（終了日）
        - 配送サイズコード"
    normal : false
rakuten :
    item_csv :
        title: コントロールカラム
        values:
        - 商品管理番号（商品URL）
        - 商品番号
        - 全商品ディレクトリID
        - タグID
        - PC用キャッチコピー
        - モバイル用キャッチコピー
        - 商品名
        - 販売価格
        - 送料
        - のし対応
        - PC用商品説明文
        - スマートフォン用商品説明文
        - PC用販売説明文
        - 商品画像URL
        - 在庫タイプ
        - 在庫数
        - カタログID
        - カタログIDなしの理由
    select_csv :
        title: 項目選択肢用コントロールカラム
        values:
        - 商品管理番号（商品URL）
        - 選択肢タイプ
        - 項目選択肢項目名
        - 項目選択肢
        - 項目選択肢選択必須"
    img_dir: https://image.rakuten.co.jp/n2-towncode/cabinet/item 