ledghome:
    csv_header :
        title: "LedgHOMEクラウド謝礼品リスト"
        values:
        - 謝礼品番号
        - 取扱年度
        - 謝礼品名
        - 謝礼品名カナ
        - 配送名称
        - ふるさとチョイス名称
        - エフレジ名称
        - 楽天名称
        - ANA名称
        - 事業者
        - 謝礼品カテゴリー
        - セット内容
        - 謝礼品紹介文
        - ステータス
        - 状態
        - 寄附設定金額
        - 価格（税込み）
        - その他経費
        - 送料
        - 送料反映
        - 発送方法
        - 取り扱い方法
        - 申込可能期間
        - 申込可能期間（開始日）
        - 申込可能期間（終了日）
        - 数量限定
        - 自由入力欄1
        - 自由入力欄2
        - その他名称1
        - その他名称2
        - その他名称3
        - 出荷依頼操作期間（開始日）
        - 出荷依頼操作期間（終了日）
        - 配送サイズコード
        - 地場産品類型
        - 類型該当理由
    normal : false
    setting :
      deliva_price_reflect : false
      teiki_price : false
choice :
    tsv_header :
        title : チョイス
        value0 :
        - （必須）容量単位
        - （必須）発送期日種別
        - （必須）会員限定
        - （必須）チョイス限定
        - （必須）クレジット決済限定
        - （必須）配送業者
        - （必須）配達日種別
        - （必須）配達日種別必須フラグ
        - （必須）配達時間指定
        - （必須）配達時間指定必須フラグ
        value1 :
        - （必須）別送対応
        - （必須）ポイント情報表示有無
        - （必須）即時交換可否
        - （必須）表示有無
        - （必須）還元率入力有無
    auth :
        user : guest
        pass : guest
        url : https://www.furusato-cms.jp/files/sample_stg_product_details.tsv

