# ==================================================

# 事業者アカウントログイン時に登録させたい項目をモーダル表示用

# ==================================================

food:
    meta : 食品取り扱い
    title : ふるさと納税の返礼品として食品を出品しますか？
    description : 出品される返礼品の中に食品が含まれる場合は「はい」を選択してください。<br>返礼品の情報をご入力いただく際のアレルギー選択項目をデフォルトで表示するかどうかに使用いたします。
