# ===================================================

# デフォルトカスタムフィールド(SS管理)

# ******* 記述法 ********
# type:text,textarea,checkbox,selectのいずれかを指定
# description:タイトル下の説明文（改行は<br>を書く）
# maxlength:文字数制限
# option:selectとcheckboxの選択肢を指定
# default:text,textareaのデフォルト値を指定
# placeholder:text,textareaのplaceholderを指定（基本的に例文を書く）

# ===================================================

# 共通:

返礼品コード:
    type: text
    placeholder: 例）AAA000

LH表示名:
    type: text
    placeholder: 例）ヒレステーキ 200g

寄附金額:
    type: number
    step: 1000
    validation: 0以外
    placeholder: 例）10000

# 固定のため変更不可
全商品ディレクトリID:
    type: rakuten-genreid
    description: 楽天登録に必要なディレクトリIDを１つ選択してください。
    validation: 必須
    min: 0
    v-model: 全商品ディレクトリID.text
    v-if: "!出品禁止ポータル.includes('楽天ふるさと納税')"
    alert: 下のボタンが無くなるまで押していかないと楽天で地味にエラーが出ます。

# 固定のため変更不可
タグID:
    type: rakuten-tagid
    description: 楽天登録に必要なタグを複数選択します。
    maxlength: 256
    validation: 必須
    v-model: タグID.text
    v-if: "!出品禁止ポータル.includes('楽天ふるさと納税')&&全商品ディレクトリID.text"
    style: 'width: 100%;height:7em;'

# 固定のため変更不可
楽天SPAカテゴリー:
    type: rakuten-spa-category
    description: 楽天SPAのカテゴリーです。RMSのカテゴリーではありません。
    validation: 必須
    v-model: 楽天SPAカテゴリー.text
    v-if: "!出品禁止ポータル.includes('楽天ふるさと納税')"
    style: 'width: 100%;height:7em;'

検索キーワード:
    type: text
    default: '検索キーワード:'
    validation: 必須
    required: required

地場産品類型:
    type: select
    option:
        1 : 1.当該地方団体の区域内において生産されたもの。
        2 : 2.当該地方団体の区域内において返礼品等の原材料の主要な部分が生産されたもの。
        3 : 3.当該地方団体の区域内において返礼品等の製造、加工その他の工程のうち主要な部分を行うことにより相応の付加価値が生じているもの。
        4 : 4.返礼品等を提供する市区町村の区域内において生産されたものであって、近隣の他の市区町村の区域内において生産されたものと混在したもの。
        5 : 5.地方団体の広報の目的で生産された当該地方団体のキャラクターグッズ、オリジナルグッズその他これらに類するものであって、形状、名称その他の特徴から当該地方団体の独自の返礼品等であることが明白なもの。
        6 : 6.前各号に該当する返礼品等と当該返礼品等との間に関連性のあるものとを合わせて提供するものであって、当該返礼品等が主要な部分を占めるもの。
        7 : 7.当該地方団体の区域内において提供される役務その他これに準ずるものであって、当該役務の主要な部分が当該地方団体に相当程度関連性のあるもの。
        8 : 8.次のいずれかに該当する返礼品等であること
        8イ : イ：市区町村が近隣の他の市区町村と共同でこれらの市区町村の区域内において前各号のいずれかに該当するものを共通の返礼品等とするもの。
        8ロ : ロ：都道府県が当該都道府県の区域内の複数の市区町村と連携し、<br>当該連携する市区町村の区域内において前各号のいずれかに該当するものを当該都道府県及び当該市区町村の共通の返礼品等とするもの。
        8ハ : ハ：都道府県が当該都道府県の区域内の複数の市区町村において地域資源として相当程度認識されているもの及び当該市区町村を認定し、当該地域資源を当該市区町村がそれぞれ返礼品等とするもの。
        9 : 9.震災、風水害、落雷、火災その他これらに類する災害により甚大な被害を受けたことにより、その被害を受ける前に提供していた前各号のいずれかに該当する返礼品等を提供することができなくなった場合において、当該返礼品等を代替するものとして提供するもの。

類型該当理由:
    type: textarea

社内共有事項:
    type: textarea
    description: この商品に関して社内共有すべきことがあればここに記入。
    placeholder: 例）よくある社内共有事項の例文
