ftp_server: ftp.rakuten.ne.jp
ftp_server_port: "16910"
upload_server: upload.rakuten.ne.jp
upload_server_port: "21"
item_csv_header:
    - コントロールカラム
    - 商品管理番号（商品URL）
    - 商品番号
    - 全商品ディレクトリID
    - タグID
    - PC用キャッチコピー
    - モバイル用キャッチコピー
    - 商品名
    - 販売価格
    - 送料
    - のし対応
    - PC用商品説明文
    - スマートフォン用商品説明文
    - PC用販売説明文
    - 商品画像URL
    - 在庫タイプ
    - 在庫数
    - カタログID
    - カタログIDなしの理由
select_csv_header:
    - 項目選択肢用コントロールカラム
    - 商品管理番号（商品URL）
    - 選択肢タイプ
    - 項目選択肢項目名
    - 項目選択肢
    - 項目選択肢選択必須
