# 楽天とLHのCSV出力時に自動変換する環境依存文字リスト

'"' : '""'
'㎝' : 'cm'
'㎜' : 'mm'
'㎏' : 'kg'
'㏄' : 'cc'
'㎖' : 'ml'
'ℓ' : 'l'
'!' : '！'
'?' : '？'
'<' : '＜'
'>' : '＞'
'(' : '（'
')' : '）'
':' : '：'
'~' : '～' # winニョロ
'吞' : '呑'
'麵' : '麺'