# デフォルトのN2の設定
n2:
    active: 0
    portal_sites:
        - ふるさとチョイス
        - 楽天ふるさと納税
formula:
    送料乗数: 0
    除数: 0.3
portal_setting:
    LedgHOME:
        カテゴリー: ''
        送料反映:
            - レターパック
            - その他
        その他経費: 利用しない
        送料: 送料を全て登録
        価格: 定期便1回ごとに登録
        eチケット: 対応する
    楽天:
        ftp_user: ''
        ftp_pass: ''
        img_dir: ''
        tag_id: '5000163/5000214/5001784/5000164/5000165/5000166/5000167/5000168/5000169/5000170/5000171/5000172'
        html: ''
        select: ''
