N2:
    稼働中: false
    LedgHOME: lhcloud
    商品タイプ:
        - 食品
    出品ポータル:
        - ふるさとチョイス
        - 楽天
    役場確認: false

寄附金額・送料:
    送料乗数: 0
    除数: 0.3
    下限寄附金額:
    送料: []

LedgHOME:
    カテゴリー:
    送料: 送料を全て登録
    送料反映:
        - レターパック
        - その他
    その他経費: 利用しない
    価格: 定期便1回ごとに登録

注意書き:
    共通:
    やきもの: "【お申し込み前に必ずお読みください】\n お届けする返礼品には個体差が生じる場合があります。下部記載の「個体差について」、「破損・欠陥について」を必ずご一読のうえ、お申し込みください。"

ふるさとチョイス:
    ポイント導入: 
    オンライン決済限定: 

楽天:
    FTP:
        user:
        pass:
    楽天SPA:
    商品画像ディレクトリ:
    共通タグID: '5000163/5000214/5001784/5000164/5000165/5000166/5000167/5000168/5000169/5000170/5000171/5000172'
    説明文追加html:
    項目選択肢:
