N2:
    稼働中: false
    LedgHOME: クラウド版レジ
    商品タイプ:
        - 食品
    出品ポータル:
        - ふるさとチョイス
        - 楽天
    ポータル共通説明文:
    役場確認: false

寄附金額・送料:
    送料乗数: 0
    除数: 0.3
    送料: []

クラウド版レジ:
    カテゴリー:
    送料: 送料を全て登録
    送料反映:
        - レターパック
        - その他
    その他経費: 利用しない
    価格: 定期便1回ごとに登録

通常版レジ:
    カテゴリー:
    価格: 定期便1回ごとに登録

ふるさとチョイス:
    ポイント導入: 
    オンライン決済限定: 

楽天:
    FTP:
        user:
        pass:
    楽天SPA:
    商品画像ディレクトリ:
    共通タグID: '5000163/5000214/5001784/5000164/5000165/5000166/5000167/5000168/5000169/5000170/5000171/5000172'
    説明文追加html:
    項目選択肢:
