---
rakuten:
  ftp:
    user: f412066-takeo
    pass: 00kK9321
  item_csv_header:
  - コントロールカラム
  - 商品管理番号（商品URL）
  - 商品番号
  - 全商品ディレクトリID
  - タグID
  - PC用キャッチコピー
  - モバイル用キャッチコピー
  - 商品名
  - 販売価格
  - 送料
  - のし対応
  - PC用商品説明文
  - スマートフォン用商品説明文
  - PC用販売説明文
  - 商品画像URL
  - 在庫タイプ
  - 在庫数
  - カタログID
  - カタログIDなしの理由
  select_csv_header:
  - 項目選択肢用コントロールカラム
  - 商品管理番号（商品URL）
  - 選択肢タイプ
  - 項目選択肢項目名
  - 項目選択肢
  - 項目選択肢選択必須
  img_dir: https://image.rakuten.co.jp/f412066-takeo/cabinet/item/
  tag_id: 5000163/5000213/5001752/5000164/5000165/5000166/5000167/5000168/5000169/5000170/5000171/5000172
  html: ""
  項目選択肢（改行区切）:
    1:
      内容: 1.ふるさと納税専用ページです。注文内容確認画面に表示される「注文者情報」を住民票情報とみなします。
      選択肢:
      - 理解した
    2:
      内容: 2.寄附金の用途を選択
      選択肢:
      - やすらぎのある長寿社会づくり
      - 子育て・教育環境づくり
      - 魅力ある市街地づくり
      - 魅力ある観光地づくり
      - 農村環境の保全と農業の確立
      - 若者の定住促進
      - スポーツ振興
      - どの分野でもかまわない
    3:
      内容: 3.ワンストップ特例申請書の送付について
      選択肢:
      - 希望する
      - 希望しない
    4:
      内容: ""
      選択肢: []
    5:
      内容: ""
      選択肢: []
...
