hasami:
    漢字: 波佐見町
    ftp_user: f423238-hasami
    ftp_pass:
    quality:
    img_dir:
    tag_id:
    

itoshima:
    漢字: 糸島市
    ftp_user: f402303-itoshima
    ftp_pass:
    quality:
    img_dir:
    tag_id:

higashisonogi:
    漢字: 東彼杵町
    ftp_user: f423211-higashisonogi
    ftp_pass:
    quality:
    img_dir:
    tag_id:

saikai:
    漢字: 西海市
    ftp_user: f422126-saikai
    ftp_pass:
    quality:
    img_dir:
    tag_id:

ojika:
    漢字: 小値賀町
    ftp_user: f423831-ojika
    ftp_pass:
    quality:
    img_dir:
    tag_id:

nagayo:
    漢字: 長与町
    ftp_user: f423076-nagayo
    ftp_pass:
    quality:
    img_dir:
    tag_id:

yoshinogari:
    漢字: 吉野ヶ里町
    ftp_user: f413275-yoshinogari
    ftp_pass:
    quality:
    img_dir:
    tag_id:

nakagawa:
    漢字: 那珂川市
    ftp_user: f402311-nakagawa
    ftp_pass:
    quality:
    img_dir:
    tag_id:

kouhoku:
    漢字: 江北町
    ftp_user: f414247-kouhoku
    ftp_pass:
    quality:
    img_dir:
    tag_id:

iki:
    漢字: 壱岐市
    ftp_user: f422100-iki
    ftp_pass:
    quality:
    img_dir:
    tag_id:

shiroishi:
    漢字: 白石町
    ftp_user: f414255-shiroishi
    ftp_pass:
    quality:
    img_dir:
    tag_id:

nagasaki:
    漢字: 長崎市
    ftp_user: f422011-nagasaki
    ftp_pass:
    quality:
    img_dir:
    tag_id:

hirado:
    漢字: 平戸市
    ftp_user: f422070-hirado
    ftp_pass:
    quality:
    img_dir:
    tag_id:

toki:
    漢字: 土岐市
    ftp_user: f212121-toki
    ftp_pass:
    quality:
    img_dir:
    tag_id:

kawatana:
    漢字: 川棚町
    ftp_user: f423220-kawatana  
    ftp_pass:
    quality:
    img_dir:
    tag_id:

ureshino:
    漢字: 嬉野市
    ftp_user: f412091-ureshino
    ftp_pass:
    quality:
    img_dir:
    tag_id:

goto:
    漢字: 五島市
    ftp_user: f422118-goto
    ftp_pass:
    quality:
    img_dir:
    tag_id:

saza:
    漢字: 佐々町
    ftp_user: f423912-saza
    ftp_pass:
    quality:
    img_dir:
    tag_id:

shinkamigoto:
    漢字: 新上五島町
    ftp_user: f424111-shinkamigoto
    ftp_pass:
    quality:
    img_dir:
    tag_id:

tajimi:
    漢字: 多治見市
    ftp_user: f212041-tajimi
    ftp_pass:
    quality:
    img_dir:
    tag_id:

minamishimabara:
    漢字: 南島原市
    ftp_user: f422142-minamisimabara
    ftp_pass:
    quality:
    img_dir:
    tag_id:

takeo:
    漢字: 武雄市
    ftp_user: f412066-takeo
    ftp_pass:
    quality:
    img_dir:
    tag_id:
