---
ftp_user: f412066-takeo
ftp_pass: 00kK9321
quality: "54"
item_csv: ""
select_csv: ""
img_dir: https://image.rakuten.co.jp/f412066-takeo/cabinet/item/
tag_id: ""
html: ""
select:
- ""
- ""
- ""
- ""
- ""
- ""
...
