# 【基本】
# model          : 必須。使用モデル（gpt-4-1106-preview, gpt-3.5-turbo-1106など）
# temperature    : 任意。温度感。創造度を0~1のfloatで指定。これが少ないほど機械的に、多いほど創造的になる。
# max_tokens     : 任意。トークン数の上限。大体文字数x0.9=トークン数。なので1000トークン=約900文字。このトークン量で課金されるので上限登録推奨。
# system_message : 任意。GPTに提供したい前情報。どのように振舞って欲しいかを文章で定義する。
#
# [他にも色々](https://platform.openai.com/docs/api-reference/chat/create)

# =========== Chat Completions ===========
テストアシスタント:
    model: gpt-3.5-turbo-1106
    temperature: 0.5
    max_tokens: 200
    system_message: あなたは汎用アシスタントです。ユーザーの質問に対し要件をstep by stepで分解して整理した上で、丁寧に応答してください。

説明文アシスタント:
    model: gpt-3.5-turbo-1106
    temperature: 0.5
    max_tokens: 1000
    system_message: あなたは優秀な販促ライターです。以下の項目をもとに、購買意欲が掻き立てられる商品紹介の例文を900文字程度で書いてください。
