########################

ふるさとチョイス:
    tsv_header :
        user : guest
        pass : guest
        url : https://www.furusato-cms.jp/files/sample_stg_product_details.tsv

########################

楽天:
    ftp_server: ftp.rakuten.ne.jp
    ftp_server_port: "16910"
    upload_server: upload.rakuten.ne.jp
    upload_server_port: "21"
    csv_header:
        item:
            - コントロールカラム
            - 商品管理番号（商品URL）
            - 商品番号
            - 全商品ディレクトリID
            - タグID
            - PC用キャッチコピー
            - モバイル用キャッチコピー
            - 商品名
            - 販売価格
            - 送料
            - のし対応
            - PC用商品説明文
            - スマートフォン用商品説明文
            - PC用販売説明文
            - 商品画像URL
            - 在庫タイプ
            - 在庫数
            - カタログID
            - カタログIDなしの理由
        select:
            - 項目選択肢用コントロールカラム
            - 商品管理番号（商品URL）
            - 選択肢タイプ
            - 項目選択肢項目名
            - 項目選択肢
            - 項目選択肢選択必須
        sku:
            item:
                - 商品管理番号（商品URL）
                - 商品番号
                - 商品名
                - 倉庫指定
                - ジャンルID
                - 非製品属性タグID
                - キャッチコピー
                - PC用商品説明文
                - スマートフォン用商品説明文
                - PC用販売説明文
                -  
                    - 商品画像タイプ%d
                    - 商品画像パス%d
                    - 商品画像（ALT）%d
                - バリエーション項目キー定義
                - バリエーション項目名定義
                -
                    - バリエーション%d選択肢定義
            option:
                - 選択肢タイプ
                - 商品オプション項目名
                -
                    - 商品オプション選択肢%d
                - 商品オプション選択必須
            sku:
                - SKU管理番号
                - システム連携用SKU番号
                -
                    - バリエーション項目キー%d
                    - バリエーション項目キーバリエーション選択肢%d
                - 販売価格
                - 再入荷お知らせボタン
                - のし対応
                - 在庫数
                - 在庫あり時納期管理番号
                - 送料
                - カタログIDなしの理由
                - SKU画像タイプ
                - SKU画像パス
                - SKU画像名（ALT）
                -
                    - 商品属性（項目）%d
                    - 商品属性（値）%d
                    - 商品属性（単位）%d

########################

LedgHOME:
    csv_header:
        - 謝礼品番号
        - 取扱年度
        - 謝礼品名
        - 謝礼品名カナ
        - 配送名称
        - ふるさとチョイス名称
        - エフレジ名称
        - 楽天名称
        - ANA名称
        - 事業者
        - 謝礼品カテゴリー
        - セット内容
        - 謝礼品紹介文
        - ステータス
        - 状態
        - 寄附設定金額
        - 価格（税込み）
        - 送料
        - 送料反映
        - 発送方法
        - 取り扱い方法
        - 申込可能期間
        - 申込可能期間（開始日）
        - 申込可能期間（終了日）
        - 数量限定
        - 自由入力欄1
        - 自由入力欄2
        - その他名称1
        - その他名称2
        - その他名称3
        - 出荷依頼操作期間（開始日）
        - 出荷依頼操作期間（終了日）
        - 配送サイズコード
        - 地場産品類型
        - 類型該当理由