########################

ふるさとチョイス:
    tsv_header :
        user : guest
        pass : guest
        url : https://www.furusato-cms.jp/files/sample_stg_product_details.tsv

########################

楽天:
    FTP:
        ftp_server: ftp.rakuten.ne.jp
        ftp_server_port: "16910"
        upload_server: upload.rakuten.ne.jp
        upload_server_port: "21"
    csv_header:
        item:
            - コントロールカラム
            - 商品管理番号（商品URL）
            - 商品番号
            - 全商品ディレクトリID
            - タグID
            - PC用キャッチコピー
            - モバイル用キャッチコピー
            - 商品名
            - 販売価格
            - 送料
            - のし対応
            - PC用商品説明文
            - スマートフォン用商品説明文
            - PC用販売説明文
            - 商品画像URL
            - 在庫タイプ
            - 在庫数
            - カタログID
            - カタログIDなしの理由
        select:
            - 項目選択肢用コントロールカラム
            - 商品管理番号（商品URL）
            - 選択肢タイプ
            - 項目選択肢項目名
            - 項目選択肢
            - 項目選択肢選択必須
        item-cat:
            - コントロールカラム
            - 商品管理番号（商品URL）
            - 表示先カテゴリ
            - 1ページ複数形式
        sku:
            item:
                - 商品管理番号（商品URL）
                - 商品番号
                - 商品名
                - 倉庫指定
                - ジャンルID
                - 非製品属性タグID
                - キャッチコピー
                - PC用商品説明文
                - スマートフォン用商品説明文
                - PC用販売説明文
                -  
                    - 商品画像タイプ%d
                    - 商品画像パス%d
                    - 商品画像名（ALT）%d
                - バリエーション項目キー定義
                - バリエーション項目名定義
                -
                    - バリエーション%d選択肢定義
            option:
                - 選択肢タイプ
                - 商品オプション項目名
                -
                    - 商品オプション選択肢%d
                - 商品オプション選択必須
            sku:
                - SKU管理番号
                - システム連携用SKU番号
                -
                    - バリエーション項目キー%d
                    - バリエーション項目キーバリエーション選択肢%d
                - 販売価格
                - 再入荷お知らせボタン
                - のし対応
                - 在庫数
                - 在庫あり時納期管理番号
                - 送料
                - カタログIDなしの理由
                - SKU画像タイプ
                - SKU画像パス
                - SKU画像名（ALT）
                -
                    - 商品属性（項目）%d
                    - 商品属性（値）%d
                    - 商品属性（単位）%d

########################

LedgHOME:
    csv_header:
        謝礼品リスト:
            - 謝礼品番号
            - 取扱年度
            - 謝礼品名
            - 謝礼品名カナ
            - 配送名称
            - ふるさとチョイス名称
            - エフレジ名称
            - 楽天名称
            - ANA名称
            - 事業者
            - 謝礼品カテゴリー
            - セット内容
            - 謝礼品紹介文
            - ステータス
            - 状態
            - 寄附設定金額
            - 価格（税込み）
            - その他経費
            - 送料
            - 送料反映
            - 発送方法
            - 取り扱い方法
            - 申込可能期間
            - 申込可能期間（開始日）
            - 申込可能期間（終了日）
            - 数量限定
            - 自由入力欄1
            - 自由入力欄2
            - その他名称1
            - その他名称2
            - その他名称3
            - 出荷依頼操作期間（開始日）
            - 出荷依頼操作期間（終了日）
            - 配送サイズコード
            - 地場産品類型
            - 類型該当理由
            - 特設サイト名称
        定期便（基本情報）リスト:
            - 定期便番号
            - 取扱年度
            - 定期便名
            - 定期便名カナ
            - ふるさとチョイス名称
            - エフレジ名称
            - 楽天名称
            - ANA名称
            - 東急名称
            - セット内容
            - 謝礼品紹介文
            - ステータス
            - 状態
            - 寄附設定金額
            - 発送方法
            - 申込可能期間
            - 申込可能期間（開始日）
            - 申込可能期間（終了日）
            - 数量限定
            - 自由入力欄1
            - 自由入力欄2
            - その他名称1
            - その他名称2
            - その他名称3
            - その他名称4
            - その他名称5
            - 自動出荷依頼予約（種別）
            - 自動出荷依頼予約（値）
        定期便（子謝礼品）リスト:
            - 定期便番号
            - 定期便名
            - 定期便種別
            - 1月1
            - 1月2
            - 1月3
            - 1月4
            - 1月5
            - 1月6
            - 1月日
            - 2月1
            - 2月2
            - 2月3
            - 2月4
            - 2月5
            - 2月6
            - 2月日
            - 3月1
            - 3月2
            - 3月3
            - 3月4
            - 3月5
            - 3月6
            - 3月日
            - 4月1
            - 4月2
            - 4月3
            - 4月4
            - 4月5
            - 4月6
            - 4月日
            - 5月1
            - 5月2
            - 5月3
            - 5月4
            - 5月5
            - 5月6
            - 5月日
            - 6月1
            - 6月2
            - 6月3
            - 6月4
            - 6月5
            - 6月6
            - 6月日
            - 7月1
            - 7月2
            - 7月3
            - 7月4
            - 7月5
            - 7月6
            - 7月日
            - 8月1
            - 8月2
            - 8月3
            - 8月4
            - 8月5
            - 8月6
            - 8月日
            - 9月1
            - 9月2
            - 9月3
            - 9月4
            - 9月5
            - 9月6
            - 9月日
            - 10月1
            - 10月2
            - 10月3
            - 10月4
            - 10月5
            - 10月6
            - 10月日
            - 11月1
            - 11月2
            - 11月3
            - 11月4
            - 11月5
            - 11月6
            - 11月日
            - 12月1
            - 12月2
            - 12月3
            - 12月4
            - 12月5
            - 12月6
            - 12月日
        税率リスト :
            - 謝礼品番号
            - 謝礼品名
            - 税区分
            - 税率
    csv_header_string:
        定期便（子謝礼品）リスト: "LedgHOMEクラウド 定期便（子謝礼品）リスト\n定期便番号,定期便名,定期便種別,1月,,,,,,,2月,,,,,,,3月,,,,,,,4月,,,,,,,5月,,,,,,,6月,,,,,,,7月,,,,,,,8月,,,,,,,9月,,,,,,,10月,,,,,,,11月,,,,,,,12月,,,,,,\n,,,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日,1,2,3,4,5,6,日\n"

########################

地場産品:
    csv_header:
        - 団体コード
        - 都道府県
        - 市区町村
        - 番号
        - 品目名
        - 必要寄附金額
        - 調達費用
        - 返礼割合
        - 地場産品基準
        - 類型該当理由
