'㎝' : 'cm'
'㎜' : 'mm'
'㎏' : 'kg'
'㏄' : 'cc'
'㎖' : 'ml'
'ℓ' : 'l'
'吞' : '呑'
'麵' : '麺'
'Ⅰ' : 'I'
'Ⅱ' : 'II'
'Ⅲ' : 'III'
'Ⅳ' : 'IV'
'Ⅴ' : 'V'
'Ⅵ' : 'VI'
'Ⅶ' : 'VII'
'Ⅷ' : 'VIII'
'Ⅸ' : 'IX'
'Ⅹ' : 'X'
'ⅰ' : 'i'
'ⅱ' : 'ii'
'ⅲ' : 'iii'
'ⅳ' : 'iv'
'ⅴ' : 'v'
'ⅵ' : 'vi'
'ⅶ' : 'vii'
'ⅷ' : 'viii'
'ⅸ' : 'ix'
'ⅹ' : 'x'
'①' : '（1）'
'②' : '（2）'
'③' : '（3）'
'④' : '（4）'
'⑤' : '（5）'
'⑥' : '（6）'
'⑦' : '（7）'
'⑧' : '（8）'
'⑨' : '（9）'
'⑩' : '（10）'
'⑪' : '（11）'
'⑫' : '（12）'
'⑬' : '（13）'
'⑭' : '（14）'
'⑮' : '（15）'
'⑯' : '（16）'
'⑰' : '（17）'
'⑱' : '（18）'
'⑲' : '（19）'
'⑳' : '（20）'
'№' : 'No.'
'㈲' : '（有）'
'㈱' : '（株）'
'㈹' : '（代）'
'㊤' : '（上）'
'㊦' : '（下）'
'㊥' : '（中）'
'㊧' : '（左）'
'㊨' : '（右）'
'㍉' : 'ミリ'
'㌔' : 'キロ'
'㌢' : 'センチ'
'㍍' : 'メートル'
'㌘' : 'グラム'
'㌧' : 'トン'
'㌃' : 'アール'
'㌶' : 'ヘクタール'
'㍑' : 'リットル'
'㍗' : 'ワット'
'㌍' : 'カロリー'
'㌦' : 'ドル'
'㌣' : 'セント'
'㌫' : 'パーセント'
'㍊' : 'ミリバール'
'㌻' : 'ページ'
'㏄' : 'cc'
'㎡' : '平方メートル'
'㍻' : '平成'
'〝' : '"'
'〟' : '"'
'℡' : 'TEL'
'㍾' : '明治'
'㍽' : '大正'
'㍼' : '昭和'
'㏍' : 'K.K.'
'髙' : '高'
'﨑' : '崎'
'彅' : 'なぎ'
'塚' : '塚'
'增' : '増'
'寬' : '寛'
'敎' : '教'
'晴' : '晴'
'朗' : '朗'
'﨔' : '欅'
'橫' : '横'
'德' : '徳'
'瀨' : '瀬'
'淸' : '清'
'瀨' : '瀬'
'凞' : '煕'
'猪' : '猪'
'益' : '益'
'礼' : '礼'
'神' : '神'
'祥' : '祥'
'福' : '福'
'靖' : '靖'
'精' : '精'
'濵' : '濱'
'琦' : '埼'
'昻' : '昂'
'緖' : '緒'
'羽' : '羽'
'薰' : '薫'
'諸' : '諸'
'賴' : '頼'
'逸' : '逸'
'郞' : '郎'
'都' : '都'
'鄕' : '郷'
'閒' : '間'
'隆' : '隆'
'靑' : '青'
'飯' : '飯'
'飼' : '飼'
'館' : '館'
'鶴' : '鶴'
'黑' : '黒'
'⻑' : '長'
'⼀' : '一'
'︕' : '！'
'⼿' : '手'
'⽔' : '水'
'⾃' : '自'
'⾻' : '骨'
'⽤' : '用'
'⿂' : '魚'
'⾷' : '食'
'⼥' : '女'
'⼤' : '大'
'⼈' : '人'
'⿐' : '鼻'
'⾹' : '香'
'⼭' : '山'
'⽇' : '日'
'⽂' : '文'
'⽣' : '生'
'⾝' : '身'
'⽸' : '缶'
'⼊' : '入'
'⽴' : '立'
'⼣' : '夕'
'⽥' : '田'
'⼾' : '戸'
'⽉' : '月'
'⼯' : '工'
'俱' : '倶'
'⽟' : '玉'
'⽩' : '白'
'醬' : '醤'
'⼲' : '干'
'⽐' : '比'
'⻨' : '麦'
'ダ' : 'ダ'
'プ' : 'プ'
'ピ' : 'ピ'
'ズ' : 'ズ'
'ブ' : 'ブ'
'ゴ' : 'ゴ'
'ド' : 'ド'
